apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: vasilij.june@gmail.com
    privateKeySecretRef:
      # Name of a secret used to store the ACME account private key
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            # If the ingressClassName field is specified, cert-manager will create new Ingress resources in order to route traffic to the acmesolver pods,
            # which are responsible for responding to ACME challenge validation requests.
            # This is the recommended way of configuring the Ingress controller.
            ingressClassName: nginx
