---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  labels:
    app: minio
spec:
  selector:
    matchLabels:
      app: minio
  serviceName: minio
  replicas: 1
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          # env:
          #   - name: MINIO_ACCESS_KEY
          #     value: "minio"
          #   - name: MINIO_SECRET_KEY
          #     value: "minio123"
          envFrom:
            - secretRef:
                name: minio-auth
          image: minio/minio:RELEASE.2023-09-30T07-02-29Z
          args:
            - server
            - /data
          ports:
            - containerPort: 9000
              hostPort: 9000
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
            initialDelaySeconds: 120
            periodSeconds: 20
          # These volume mounts are persistent. Each pod in the StatefulSet
          # gets a volume mounted based on this field.
          volumeMounts:
            - name: data
              mountPath: /data
  # These are converted to volume claims by the controller
  # and mounted at the paths mentioned above.
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: standard
        resources:
          requests:
            storage: 10Gi
